name: flutter_task_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get: 4.6.5
  http: 0.13.3
  path: 
  sqflite: ^2.2.8+4
  url_launcher: 6.1.7

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
